name: "Setup"
description: "Set up a workspace"
inputs:
  - name: Use Node.js 10 x64
    uses: actions/setup-node@v2-beta
    with:
      node-version: 10
      architecture: x64
  - run: yarn install --frozen-lockfile
