# This workflow will install node dependencies, build the source code and run the test target

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        node_version:
          - 10
        architecture:
          - x64

    name: Node ${{ matrix.node_version }} - ${{ matrix.architecture }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2-beta
      with:
        node-version: ${{ matrix.node_version }}
        architecture: ${{ matrix.architecture }}
    - run: yarn install --frozen-lockfile
    - if: ${{ runner.os == 'windows-latest' }}
      run: npm config set script-shell "C:\\Program Files\\git\\bin\\bash.exe"
    # see: https://github.com/stackgl/headless-gl#how-can-headless-gl-be-used-on-a-headless-linux-machine
    - if: ${{ runner.os == 'ubuntu-latest' }}
      run: xvfb-run -s "-ac -screen 0 1280x1024x24" yarn test
    - if: ${{ runner.os != 'ubuntu-latest' }}
      run: yarn test

