# This workflow will install node dependencies, build the source code and run the test target

name: Node.js CI

on: [push, pull_request]

jobs:
  build:

    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        node_version:
          - 10
        architecture:
          - x64

    name: Node ${{ matrix.node_version }} - ${{ matrix.architecture }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
    # On windows git checkout automatically converts to CRLF, which eslint complains about
    - name: Set git to use LF
      run: |
        git config --global core.autocrlf false
        git config --global core.eol lf
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2-beta
      with:
        node-version: ${{ matrix.node_version }}
        architecture: ${{ matrix.architecture }}
    - run: yarn install --frozen-lockfile
    - if: ${{ matrix.os == 'ubuntu-latest' }}
      run: xvfb-run -s "-ac -screen 0 1280x1024x24" yarn test
    - if: ${{ matrix.os != 'ubuntu-latest' }}
      run: yarn test

