# This workflow will install node dependencies, build the source code and run the test target

name: Node.js CI

on: [push, pull_request]
  # push:
  #   branches: [ main ]
  # pull_request: 
  #   branches: [ main ]

jobs:
  build:

    strategy:
      fail-fast: false
      matrix:
        os:
          # - ubuntu-latest
          # - macos-latest
          - windows-latest
        node_version:
          - 10
        architecture:
          - x64

    name: Node ${{ matrix.node_version }} - ${{ matrix.architecture }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2-beta
      with:
        node-version: ${{ matrix.node_version }}
        architecture: ${{ matrix.architecture }}
    - run: yarn install --frozen-lockfile
    - if: ${{ runner.os == 'ubuntu-latest' }}
      run: xvfb-run -s "-ac -screen 0 1280x1024x24" yarn test
    - if: ${{ runner.os != 'ubuntu-latest' }}
      run: chmod +x build/run-tap
    - if: ${{ runner.os != 'ubuntu-latest' }}
      run: yarn test-unit

